### ISSUE TITLE
Gather bot training data

### ISSUE THREAD

**Issue by JL-597586** [JL-597586/Virtual-TA-Group-12-4485-#5]
Description: Determine bot training requirements
Acceptance criteria: Must account for training FAQ
Definition of Ready: No dependencies

**Comment by Astryderneal** [comment]
Progress so far: Identify content and possible sources for training bot. Research and gathering in progress

**Comment by Astryderneal** [comment]
Gathered many sets of data, compiling data into forms readable by the bot: text document answers, text document question/answers, and excel spreadsheet
